apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 19090
      targetPort: 19090
