# permissions for end users to view scalablepods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scalablepod-viewer-role
rules:
- apiGroups:
  - scalable.scalablepod.tutorial.io
  resources:
  - scalablepods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scalable.scalablepod.tutorial.io
  resources:
  - scalablepods/status
  verbs:
  - get
