apiVersion: v1
kind: Service
metadata:
  name: user-facing-service
spec:
  type: NodePort
  selector:
    app: user-facing-server
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080